name: age
description: Calculate the age based on date diffs.
version: 1.0.0
#author:
homepage: https://github.com/edgarfroes/age

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter: